[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
package = "/.netlify/netlify-plugin-jest"

[[plugins]]
package = "netlify-plugin-subfont"
  [plugins.inputs]
  entryPoints = ["dist/*.html"]
