[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@seancdavis/netlify-plugin-jest"

[[plugins]]
  package = "@seancdavis/netlify-plugin-github-dispatch"

[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
    [plugins.inputs]
      fileFilter = ['index.html']
      directoryFilter = ['!*']

[[plugins]]
  package = "netlify-plugin-a11y"
    [plugins.inputs]
      checkPaths = ['/', '/about']
      resultMode = "warn"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "dist"
    trailingSlash = true
    exclude = [
      "./dist/404.html",
      "./dist/search/index.html",
      "./dist/demos/**/**"
    ]
