name: Notion Post Publisher
on: [workflow_dispatch]
jobs:
  Notion-Post-Publisher:
    name: "Notion Post Publisher"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: yarn install
      - name: Process pending posts
        run: |
          cd www
          npm run publish-posts
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "[Bot] New Post(s) from Notion"
          body: ":robot: This pull request was opened automatically by a GitHub Action after running the Notion post publisher script."
          labels: "content,feature: blog"
          commit-message: New post from  Notion
