name: Performance
on: [workflow_dispatch]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Run Lighthouse CI
        run: |
          cd www
          ./node_modules/.bin/lhci autorun
      - name: Print Results
        run: |
          cd www
          node ./scripts/printLighthouseScores.js
