name: Performance
on: [workflow_dispatch]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: pnpm install
      - name: Run Lighthouse CI
        run: ./node_modules/.bin/lhci autorun
      - name: Print Results
        run: node ./scripts/printLighthouseScores.js
