name: Update Visual Regression Snapshots
on:
  push:
    branches:
      - main
    paths:
      - website/**
jobs:
  Update-Visual-Regression-Snapshots:
    name: "Update Visual Regression Snapshots"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: npm run pretest:visual
        env:
          IMGIX_DOMAIN: ${{ secrets.IMGIX_DOMAIN }}
          IMGIX_TOKEN: ${{ secrets.IMGIX_TOKEN }}
      - name: Run tests
        # Note: Shouldn't need env vars because the site is already built and we
        # won't have any failures. We're committing to the repo directly.
        run: JEST_CONFIG=visual ELEVENTY_ENV=test ./node_modules/.bin/jest --updateSnapshot
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update jest snapshots"
          commit_user_name: Sean C Davis
          commit_user_email: scdavis41@gmail.com
          commit_author: Sean C Davis <scdavis41@gmail.com>
          branch: ${{ github.head_ref }}
