name: Visual Regression
on: [workflow_dispatch, pull_request]
jobs:
  Run-Visual-Regression:
    name: "Run Visual Regression"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: npm run test:visual
        env:
          IMGIX_DOMAIN: ${{ secrets.IMGIX_DOMAIN }}
          IMGIX_TOKEN: ${{ secrets.IMGIX_TOKEN }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
